# -*- coding: utf-8 -*-

ETHER_DIVISOR = 1000000000

MIMETYPES_IMAGENS_ACEITOS = ["image/jpeg", "image/png"]

NODO_TAMANHO_IMAGEM_LISTAGEM_LARGURA = 400
NODO_TAMANHO_IMAGEM_LISTAGEM_ALTURA = 400

NODOS_TAMANHO_IMAGEM_LISTAGEM_LARGURA = 500
NODOS_TAMANHO_IMAGEM_LISTAGEM_ALTURA = 315

OBJETO_TAMANHO_IMAGEM_LISTAGEM_LARGURA = 400
OBJETO_TAMANHO_IMAGEM_LISTAGEM_ALTURA = 400
