# -*- coding: utf-8 -*-

MIMETYPES_IMAGENS_ACEITOS = ["image/jpeg", "image/png"]

NODOS_TAMANHO_IMAGEM_LISTAGEM_LARGURA = 500
NODOS_TAMANHO_IMAGEM_LISTAGEM_ALTURA = 315

OBJETO_TAMANHO_IMAGEM_LISTAGEM_LARGURA = 400
OBJETO_TAMANHO_IMAGEM_LISTAGEM_ALTURA = 400
