# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodos',
            name='contato_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='nodos',
            name='contato_whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
    ]
