# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_auto_20170518_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnodos',
            name='imagem_detalhes',
        ),
        migrations.RemoveField(
            model_name='historicalnodos',
            name='imagem_listagem',
        ),
        migrations.RemoveField(
            model_name='historicalnodos',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='historicalobjeto',
            name='imagem_detalhes',
        ),
        migrations.RemoveField(
            model_name='historicalobjeto',
            name='imagem_listagem',
        ),
        migrations.RemoveField(
            model_name='historicalobjeto',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='nodos',
            name='imagem_detalhes',
        ),
        migrations.RemoveField(
            model_name='nodos',
            name='imagem_listagem',
        ),
        migrations.RemoveField(
            model_name='nodos',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='imagem_detalhes',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='imagem_listagem',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='titulo',
        ),
        migrations.AddField(
            model_name='historicalnodos',
            name='contato_zoom',
            field=models.URLField(blank=True, null=True, verbose_name='Zoom'),
        ),
        migrations.AddField(
            model_name='historicalnodos',
            name='imagem',
            field=models.TextField(blank=True, help_text='Dimens\xf5es da imagem: 300 pixels x 300 pixels', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalnodos',
            name='resumo',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Resumo'),
        ),
        migrations.AddField(
            model_name='historicalobjeto',
            name='contato_zoom',
            field=models.URLField(blank=True, null=True, verbose_name='Zoom'),
        ),
        migrations.AddField(
            model_name='historicalobjeto',
            name='imagem',
            field=models.TextField(blank=True, help_text='Dimens\xf5es da imagem: 50 pixels x 50 pixels', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nodos',
            name='contato_zoom',
            field=models.URLField(blank=True, null=True, verbose_name='Zoom'),
        ),
        migrations.AddField(
            model_name='nodos',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Dimens\xf5es da imagem: 300 pixels x 300 pixels', null=True, upload_to='imagens/nodos/listagem'),
        ),
        migrations.AddField(
            model_name='nodos',
            name='resumo',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Resumo'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='contato_zoom',
            field=models.URLField(blank=True, null=True, verbose_name='Zoom'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Dimens\xf5es da imagem: 50 pixels x 50 pixels', null=True, upload_to='imagens/objetos/listagem'),
        ),
        migrations.AlterField(
            model_name='historicalnodos',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da Comunidade'),
        ),
        migrations.AlterField(
            model_name='historicalobjeto',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Objeto'),
        ),
        migrations.AlterField(
            model_name='nodos',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da Comunidade'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Objeto'),
        ),
    ]
