# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_auto_20170704_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnodo',
            name='carteira',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Hash Carteira'),
        ),
        migrations.AddField(
            model_name='historicalnodo',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='carteira',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Hash Carteira'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalnodos',
            name='imagem',
            field=models.TextField(blank=True, help_text='Dimens\xf5es da imagem: 500 pixels x 315 pixels', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalobjeto',
            name='imagem',
            field=models.TextField(blank=True, help_text='Dimens\xf5es da imagem: 400 pixels x 400 pixels', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nodos',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Dimens\xf5es da imagem: 500 pixels x 315 pixels', null=True, upload_to='imagens/nodos/listagem'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Dimens\xf5es da imagem: 400 pixels x 400 pixels', null=True, upload_to='imagens/objetos/listagem'),
        ),
    ]
