# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_historicalnodo_historicalnodos_historicalobjeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnodos',
            name='imagem',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalobjeto',
            name='imagem',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nodos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/nodos'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/objetos'),
        ),
    ]
