# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_auto_20170516_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalnodos',
            old_name='imagem',
            new_name='imagem_listagem',
        ),
        migrations.RenameField(
            model_name='nodos',
            old_name='imagem',
            new_name='imagem_listagem',
        ),
    ]
