# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_auto_20170710_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnodo',
            name='contato_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='historicalnodo',
            name='contato_whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='historicalnodo',
            name='contato_zoom',
            field=models.URLField(blank=True, null=True, verbose_name='Zoom'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='contato_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='contato_whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='contato_zoom',
            field=models.URLField(blank=True, null=True, verbose_name='Zoom'),
        ),
    ]
