# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_auto_20170516_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnodos',
            name='imagem_detalhes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nodos',
            name='imagem_detalhes',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/nodos/detalhes'),
        ),
        migrations.AlterField(
            model_name='nodos',
            name='imagem_listagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/nodos/listagem'),
        ),
    ]
