# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_auto_20170516_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalobjeto',
            old_name='imagem',
            new_name='imagem_listagem',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='objeto',
            name='imagem_listagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/nodos/listagem'),
        ),
    ]
