# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_auto_20170710_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalnodo',
            old_name='foto',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='nodo',
            old_name='foto',
            new_name='imagem',
        ),
    ]
