# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_auto_20170516_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjeto',
            name='imagem_detalhes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objeto',
            name='imagem_detalhes',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/objetos/detalhes'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='imagem_listagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/objetos/listagem'),
        ),
    ]
