# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_auto_20170710_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnodo',
            name='quem_sou',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Quem Sou?'),
        ),
        migrations.AlterField(
            model_name='nodo',
            name='quem_sou',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Quem Sou?'),
        ),
    ]
