# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_auto_20170710_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carteira', models.CharField(max_length=42, unique=True, verbose_name='Hash da Carteira')),
                ('total', models.FloatField()),
            ],
        ),
    ]
