# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_auto_20170713_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnodo',
            name='telefone',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='telefone',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='Telefone'),
        ),
    ]
