# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_auto_20170714_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnodo',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sujeito'},
        ),
        migrations.AlterModelOptions(
            name='historicalnodos',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Comunidade'},
        ),
        migrations.AlterModelOptions(
            name='nodo',
            options={'verbose_name': 'Sujeito'},
        ),
        migrations.AlterModelOptions(
            name='nodos',
            options={'verbose_name': 'Comunidade'},
        ),
        migrations.AlterField(
            model_name='historicalnodos',
            name='nome',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Nome da Comunidade'),
        ),
        migrations.AlterField(
            model_name='historicalobjeto',
            name='nome',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Nome do Objeto'),
        ),
        migrations.AlterField(
            model_name='nodos',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome da Comunidade'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nome do Objeto'),
        ),
        migrations.AlterUniqueTogether(
            name='objeto',
            unique_together=set([('nodos', 'nome')]),
        ),
    ]
