# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_auto_20170719_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnodo',
            name='excluido_por',
        ),
        migrations.RemoveField(
            model_name='historicalnodo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnodo',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalNodo',
        ),
    ]
